#!/bin/bash
set -e

RUNENV=${1:-production}
ERP_HOST=${ERP_HOST:-'172.17.42.1'}

sed -i "s/localhost/${ERP_HOST}/" /srv/barakafrites/config/config.yml

/bin/bash -l -c 'rvm gemset use barakafrites'
/bin/bash -l -c "RAILS_ENV=$RUNENV rake db:create"
/bin/bash -l -c "RAILS_ENV=$RUNENV rake db:migrate"
/bin/bash -l -c "bundle exec puma -e $RUNENV -b tcp://0.0.0.0:9292 -p /srv/barakafrites/run/puma.pid -d"

while ( true ); do
        echo '##################################'
        echo 'To detach from Docker Console:'
        echo '  -> Ctrl-p + Ctrl-q.'
        echo
        echo 'Dropping to rails console'
        echo '##################################'
        echo
        sleep 1
        /bin/bash -l -c "HOME=/srv/barakafrites RAILS_ENV=$RUNENV bundle exec ./script/rails c"
done
