development:
  open_object:
    host: 'octm-dev.siclic.fr'
    port: '8069'
    common: '/xmlrpc/common'
    object: '/xmlrpc/object'
  root_menu: 'OpenSTM'
  credential_expiration_hours: 12
test:
  open_object:
    host: 'octm-dev.siclic.fr'
    port: '8069'
    common: '/xmlrpc/common'
    object: '/xmlrpc/object'
  root_menu: 'OpenSTM'
  credential_expiration_hours: 12


production:
  open_object:
    host: 'octm-dev.siclic.fr'
    port: '8069'
    common: '/xmlrpc/common'
    object: '/xmlrpc/object'
  root_menu: 'OpenSTM'
  credential_expiration_hours: 12
