development:
  open_object:
    host: 'octm-dev.siclic.fr'
    port: '8069'
    common: '/xmlrpc/common'
    object: '/xmlrpc/object'
  root_menu: 'OpenSTM'

test:
  open_object:
    host: 'octm-dev.siclic.fr'
    port: '8069'
    common: '/xmlrpc/common'
    object: '/xmlrpc/object'
  root_menu: 'OpenSTM'


production:
  open_object:
    host: 'octm-dev.siclic.fr'
    port: '8069'
    common: '/xmlrpc/common'
    object: '/xmlrpc/object'
  root_menu: 'OpenSTM'
